"""add fk accountid to table Visit

Revision ID: 9a5f22f65e1e
Revises: 
Create Date: 2023-04-25 19:13:58.243944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '9a5f22f65e1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Account_AccountName', table_name='Account')
    op.alter_column('OtherDisease', 'FK_VisitID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('OtherMedicine', 'FK_VisitID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('Patient', sa.Column('Alert', mssql.BIT(), nullable=True))
    op.alter_column('RebuildData', 'FK_CreateTime',
               existing_type=sa.NCHAR(length=19),
               nullable=False)
    op.alter_column('Thymus', 'FK_PatientID',
               existing_type=sa.NCHAR(length=10),
               nullable=False)
    op.alter_column('Visit', 'FK_PatientID',
               existing_type=sa.NCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Visit', 'FK_PatientID',
               existing_type=sa.NCHAR(length=10),
               nullable=True)
    op.alter_column('Thymus', 'FK_PatientID',
               existing_type=sa.NCHAR(length=10),
               nullable=True)
    op.alter_column('RebuildData', 'FK_CreateTime',
               existing_type=sa.NCHAR(length=19),
               nullable=True)
    op.drop_column('Patient', 'Alert')
    op.alter_column('OtherMedicine', 'FK_VisitID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('OtherDisease', 'FK_VisitID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_Account_AccountName', 'Account', ['AccountName'], unique=False)
    # ### end Alembic commands ###
